
inp = struct( ...
	'hpf_sec', '300', ...
	'motpar1_txt', '../../OUTPUTS/motpar1.txt', ...
	'motpar2_txt', '../../OUTPUTS/motpar2.txt', ...
	'out_dir', '../../OUTPUTS', ...
	'trialreport_csv', '../../OUTPUTS/trialreport.csv', ...
	'swfmri1_nii', '../../OUTPUTS/swctrrfmri1.nii', ...
	'swfmri2_nii', '../../OUTPUTS/swctrrfmri2.nii', ...
	'biasnorm_nii', '../../OUTPUTS/biasnorm.nii' ...
	);

first_level_stats_cue_mu3_feedback_epsi3_orth1(inp);
